/*
 * generated by Xtext 2.25.0
 */
package ca.uottawa.csmlab.symboleo;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.parser.antlr.ISyntaxErrorMessageProvider;

import ca.uottawa.csmlab.symboleo.validation.SymboleoSyntaxErrorMessageProvider;
import ca.uottawa.csmlab.symboleo.validation.SymboleoValueConverters;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SymboleoRuntimeModule extends AbstractSymboleoRuntimeModule {
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return SymboleoValueConverters.class;
  }

  public Class<? extends ISyntaxErrorMessageProvider> bindISyntaxErrorMessageProvider() {
    return SymboleoSyntaxErrorMessageProvider.class;
  }
}
